services:
  trend-whisperer:
    build: .
    env_file:
      - path: .env
        required: false
    volumes:
      - ./src/data:/home/app/trend-whisperer/src/data
      - ./reports:/home/app/trend-whisperer/reports
